unifi-pkg_secrets: null
sops:
  lastmodified: "2026-04-13T02:48:58Z"
  mac: ENC[AES256_GCM,data:Dm9pPbS/lFnA2VvzwHoET1t/nwbmAUd9LtLqGQ5ulryc1A772bF7Ow3n+JzPPSWtejJ+k9FVLpoRTdExcA8QRZMGed3f2erwvsLIpyXFsFOyYzCw+XG2629uo99/u18TbE9LEQ8fMU453btOghN9IasryGqRKp4A8kapqhDRSyg=,iv:elNaZik9v+nxM8B21AleygkM5Hhpmo2I7Pyd7RtWyI0=,tag:fU0osvTTaPb+wI+Akz0m0Q==,type:str]
  pgp:
    - created_at: "2026-04-13T02:48:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv6AwEJRFPjb5OsJT0zejxCUGuzsxnmBc2OITE0DMnuAAdg
        CeiC4+5SVWhw9teHUAr93v610zZx8VgxAEgg/lM8vNA3WQH2h3KQoQVoeSDBrSlv
        iMQDls4/18MQQI+mQh47yYXbB81MxkpdAmStFF102iHQTyHMKgDmNNz459kLNrwN
        spEcl5Ihen8+BcaSKXFNGcQFSkTw51CP+YDcy2msB7wdKV2GmwdAcY4ykbLp22tu
        8f+l5F2b39Z2k1vgxRImTquinHB8x2iIGf7Ovz1UipvClGhqKb7ggXxIS2mGfBKr
        Mj+fkUK3lt1olBtbzZLv7K0QNvfSprzofc15z70ZY0Uko0PIK7ccz9RIgzXWMTFN
        pup7lm659wRpys11A31KaHuCqvMExhzxV5qIjVmhyRZ9nUZaQVIl0w4njqhTra7P
        tASsRCW/aaud9VIsoaTsw3DvO+CsmMSmiQJKfsJ1FD1Et8tQcBUgS9dOb7EfELcP
        DaciF8Ki2218MZ9IuzWS0l4BrINEdFsPvVHoVM9A1cTc0JZROfjKZixQ2Xppr+LA
        P9R9VEccE1tso4HWrCd9CWEzZSkMeepYANdsfxKrGQ6dXnMY3EKzWTr3HQrP4UaL
        9wYaremee7HWHpptEONp
        =pkRP
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-13T02:48:58Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ/9H8Vykul4PEAptByruahNN6M7qrsxaBARBb4w6nzZZQBm
        nPH5FZ6HTIAB/2E1iU489P9zptGxdGhFvI6FZe3AhedVCLrXDuu6srcEDsNrddBx
        ugrJBl1BDEvGQgNUFDe2uhcYFBNGCgieLa6hT+k0jeopxJH74Vf0OGB6JDJAzb7T
        qflp1boEDeYi4ZQ6i2DKM0fLKnl5Hg0QI6CycUQL/c1Zf+owELRP51islIs9VE7b
        DXTNzVRj02//j3GGBbnmsWP8fkTF9VSSfLMPhQx8WSeEYZYQpiStpKgP1n8OY5Xm
        uB2U1QcgPaJjfl/KEvrhJB5sdsIYX7C+cU5ESgAAVvsy+/RtGIUmqVUwUmi9GJm/
        h0FhEeTqkK7EblGslD9AxHM3isCqI7RlFnBeXi7ygEu7nU5LokjfNEF779Tgj/Wx
        WYUp5nPz5UmS9FxpWm9bfXw0ZiaIqFdYyVvlR+rXMjTQDgba5tp1q64yBqsPoDTH
        BlDdNHdMAW0zMffngZT6s28FJMywg9dm9J15EjrmVrigQdvSkV2aJt/pqfLUBXvV
        wqWd4A3l0g+EsV6DE5X2YdeZqTb1Yakcvy+h/pDUmpqM8TgnZEKtDXqlPJCa834j
        xi8fOV2A4Jm0AzwiNBU334mJA3dMMOl1ABaEdxp8A9CaBMV/BIfTu7/Gq6m1hZvS
        XgF4j43QSwzW2s88LWJZJ1Xn6A7tNZjgKCBAchGiQ5Rl0me3RCmhRivClVff/Y1B
        i7InOH5CapSdRZNX2aiV7nF5jcyQi1wTzmm2nDFBFsrxeMH0h5aha+jCX5Zr+Fk=
        =dM/1
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
