framework_packages:
- name: _framework-pkg
  package_type: external
  exportable: true
  repo: de3-framework-pkg-repo
  source: https://github.com/philwyoungatinsight/de3-framework-pkg-repo.git
  git_ref: main
- name: unifi-pkg
  package_type: embedded
  exportable: true
  is_main_package: true
