gcp_seed_secrets:
  billing_id: ENC[AES256_GCM,data:XFEiuCma3jHvyqYg7kttcmi3Ldg=,iv:6hEpYJrCCaCVP1DOJI4lEYdQsBj+ViCmn9LjPRsAiHA=,tag:WdRM1S1w3ZnAry2s1PcdRg==,type:str]
  sa_name: ENC[AES256_GCM,data:ofLB2RgmIaR6ZQDJ+Q==,iv:3dqu/aJ+4Fu/q1Sea6RpLJ7PbEQqFbGBzN5lzOcgXEQ=,tag:lctkfthBajEBX39BwV236w==,type:str]
sops:
  lastmodified: "2026-04-08T20:09:56Z"
  mac: ENC[AES256_GCM,data:sfGIAjJTvNbWjSobrEkGxFbQ3zri+3F+QoJTs5NHUK/bGQzJVe5eqvPNUZlUWwBaJ1Bu7u1zNFkWRxzo7C37Dqf6wsql2BjfmFzTWrgreEC3S7ffkXj7rpGGWLSn+1pQwZy/bsTvWZtm+uWUE9WRvSiHfX0A5uFPKtkU+3zHOLY=,iv:Col2Z/I4OPXr+7mYLssQVjMAazlm6+PYZK4UDlcO+ss=,tag:SVsMycEY2db+TjoXNX2VEg==,type:str]
  pgp:
    - created_at: "2026-04-08T20:09:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQGMAweuHx4I2A4UAQv8CveBCakBNFIfgcmwuGWVBuWLCHaEHdLTbFepx7R73vDn
        KIt5K0kZMMpTVCYm6cP37ygyeOhjRexPBgP03/+RinbcsBuN4R9aalZ+OSKwM/pl
        eh4gjWuc+NXfyGoBabJoCADi0d767HxI7Q7prz75gudg3nk5Pf9bfLzPDIrvZAzt
        1h2bWhWrcUPg/qUcJ39gSY6UwP+cPS83NAePSE0yV17jRGnNmSI9GpSqR8+begRi
        qxwX0XjO203gv2bqAy449al+O1HJ96g6Jp385FGG89CeEczt2ELIiIvffzD6J1jm
        bJ3L0Nu33ZOnT7mK9oU45n1zG8czowvESXpTTeKETpt1erwyANzWtoB4IoRSHUx/
        iFermh4CjNPm3EdihNEBHmq9cm5iujq/F8j64hUeKDWtDW74Pd3/uFPZyIq7+9sD
        hiUvGZ62fgbTcUwyPumzY5F4jVvoanzhkXOMnhna/dB5Du1wTPiFK4FXVrfeOFRl
        UI0hBWW3m8Ue4kH5vOIv0l4BBxyEKvgwEMckOHThO1Kc1xB8gGgKyCd8L6Ndhk6c
        ORtfwlyhJiLaT69w6URHIa8oyUoVdWc7sSQj6GshC9HVkiuiXKzdIr2Jz1GvfbQR
        7X0Rmihv5l3Qs//POpxn
        =I1JZ
        -----END PGP MESSAGE-----
      fp: 446B4127CF4E00C389579F20986E9FAE2FB2BEBD
    - created_at: "2026-04-08T20:09:56Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA1MQLyG6dlTlAQ/9G5KiMWTHDp227ZWo6L0A6E5f+JR6vuxPXFsESBr1lAqK
        b3ZFlgdINuHDx8iHmtvBJtwruMt1kV1uxv+L2hv3S2yIK/Q+zI4kaP8uiVoTEODI
        +3khAZ8e2JF/Lf6nbbASD+3HW0J6FXW86wreLVPTHqF4ITJFbdpWRcuOUERDcVPn
        Wd1yI9LcHxKerzA2A6f+SKNgQVt/wFm9lugP5hdICtWUW3qa1Mb20W73ypFKSoes
        o8XI/dCaKsledzglvuLmnEFbFKMspnsKlylqmW4axNuSCppFIRVTqgfluWqjSiV0
        aSE+7NfgeefWeovv7Xum3mEE3QYlw5qN9H2SgAFfpCJPsI0/vEb7lS5iVKvgzY6m
        Ja3CKpYhYQHfSEueX1ghx4fhYkrsRVMTfdbOwt2PVdUjZf20NG1OgZS1fXexUJXm
        3gL06hxdP1Lk+Bn/OrvltdV6VDuV7W7cY1rgjluMlKNQzh2Z7c8QEVVn9BoKYggb
        jNdMARqZO8SkNvwfPOmdz6/4pM/1W7y0m7XNxYDwy3BA8fNE3zeMmlybUTb/Eupx
        FJ9L8IjxaHwsaiP71kfBuSRMngEAMRcB5Dv+jH0Or2Y0peNFjQTp3Z87+O67AsTD
        myoopVSEguy4flVbiV64wRtG8bU1PgD/I6ttV066VaRquA+Bh7NXLcTEPN8jiijS
        XgEYIrlS2+PqEuPY2Z2m6z+JXYS4T8L9qnDRzFZhRp3T6E/W1lnetoMEOtCZE9hp
        2ZzxL/ja1zpdzzYZoI6uZxt/38OJBGfHFJauAjiJK2gGBjFHHV0qH3vYDFm6KM8=
        =LyPS
        -----END PGP MESSAGE-----
      fp: 1FAFFDF2C76C758F736178E2B776DF4CEB6B692B
  unencrypted_suffix: _unencrypted
  version: 3.10.2
